/***********************************************************************/
/*                                                                     */
/*  FILE        :functiongenerator.cpp                                 */
/*  DATE        :Fri, May 08, 2015                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :29                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

void main(void);

void main(void)
{
	
}
