//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ANoise.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "ANoise.hpp"
#include "Settings.hpp"

ANoise::ANoise(unsigned int freq, unsigned int phase, float gain)
	:count(0)
{
	
}

unsigned int ANoise::GetValueNow() {
	
}

unsigned char ANoise::GetId() {
	return Settings::WAVE_ID_ANOISE;
}

