//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ANone.cpp
//  @ Date : 2015/05/22
//  @ Author : 
//
//


#include "ANone.hpp"
#include "Settings.hpp"

unsigned int ANone::GetValueNow() {
	return 0;
}


unsigned char ANone::GetId() {
	return Settings::WAVE_ID_ANONE;
}

