//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ANone.cpp
//  @ Date : 2015/05/22
//  @ Author : Kazuki Kikuchi
//
//


#include "ANone.hpp"
#include "Settings.hpp"

ANone::ANone(){
	;
}

unsigned int ANone::GetValueNow() {
	return 0;
}


unsigned char ANone::GetId() {
	return Settings::WAVE_ID_ANONE;
}

