//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : APWM.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "APWM.hpp"
#include "Settings.hpp"

APWM::APWM(unsigned int freq, float phase, unsigned int gain) 
	: m_thre_point(0), AWave(0xA4)
{
	SetGain(gain);
	m_clk.Set(freq, 100, phase);
	ID = Settings::WAVE_ID_APWM;
	duty = 0;
}

void APWM::SetDuty(float d){
	duty = d;
	m_thre_point = (unsigned int)(d * (float) m_clk.GetNop());
}

float APWM::GetDuty(){
	return duty;
}

unsigned int APWM::GetValueNow() {
	return (m_clk.Update() < m_thre_point) ? 0xFFE : 0;
}

unsigned char APWM::GetId() {
	return Settings::WAVE_ID_APWM;
}


