//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : APWM.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "APWM.hpp"
#include "Settings.hpp"

APWM::APWM(unsigned int freq, unsigned int phase, float gain) 
	: m_thre_point(0)
{
	SetGain(gain);
	m_clk.Set(freq, 256, phase);
}

void APWM::SetDuty(float d){
	m_thre_point = (d * (float) m_clk.GetNop());
}

unsigned int APWM::GetValueNow() {
	return (m_clk.Update() < m_thre_point) ? 4096 : 0;
}

unsigned char APWM::GetId() {
	return Settings::WAVE_ID_APWM;
}


