//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ASawtooth.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "ASawtooth.hpp"
#include "Settings.hpp"

ASawtooth::ASawtooth(unsigned int freq, unsigned int phase, float gain) {
	SetGain(gain);
	m_clk.Set(freq, 64, phase);
	m_dv = (float) 0xFFF / (float)m_clk.GetNop();
}

unsigned int ASawtooth::GetValueNow() {
	return (unsigned int)(m_clk.Update() * );
}

unsigned char ASawtooth::GetId() {
	return Settings::WAVE_ID_ASAWTOOTH;
}

