//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ASawtooth.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "ASawtooth.hpp"
#include "Settings.hpp"

ASawtooth::ASawtooth(unsigned int freq, unsigned int phase, float gain) {
	SetGain(gain);
	m_clk.Set(freq, 256, phase);
}

unsigned int ASawtooth::GetValueNow() {
	return (unsigned int)(4096.0 * (float) m_clk.Update() / (float) (m_clk.GetNop() - 1));
}

unsigned char ASawtooth::GetId() {
	return Settings::WAVE_ID_ASAWTOOTH;
}

