//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ASine.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "ASine.hpp"

unsigned int ASine::GetValueNow() {

}

unsigned char ASine::GetId() {

}

ASine::ASine(const unsigned int *stale, unsigned int nop, unsigned int freq, unsigned int phase, float gain) {

}

