//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ATriangle.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "ATriangle.hpp"
#include "Settings.hpp"

ATriangle::ATriangle(unsigned int freq, unsigned int phase, float gain)
	: m_is_countup(true)
{
	SetGain(gain);
	m_clk.Set(freq, 4096, phase);
}

unsigned int ATriangle::GetValueNow() {
	return (m_is_countup) ? m_clk.Update() : (4096 - m_clk.Update());
}

unsigned char ATriangle::GetId() {
	return Settings::WAVE_ID_ATRIANGLE;
}


