//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ATriangle.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "ATriangle.hpp"

unsigned int ATriangle::GetValueNow() {

}

unsigned char ATriangle::GetId() {

}


ATriangle::ATriangle(unsigned int freq, unsigned int phase, float gain) {

}

