//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : AWave.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "AWave.hpp"

AWave::AWave()
	: m_A(1.0)

{

}


void AWave::SetGain(float gain) {
	m_A = gain;
}

float AWave::GetGain() {
	return m_A;
}

void AWave::SetPhase(float phain) {
	m_clk.SetPhase(phain);
}

float AWave::GetPhase() {
	return m_clk.GetPhase();
}

void AWave::SetFrequency(unsigned int fin) {
	m_clk.SetFreq(fin);
}

unsigned int AWave::GetFrequency() {
	return m_clk.GetFreq();
}

unsigned int AWave::GetValueNow() {
	;
}

unsigned char AWave::GetId() {
	;
}

