//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : BNoise.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "BNoise.hpp"

unsigned int BNoise::GetValueNow() {

}

unsigned char BNoise::GetId() {

}

unsigned int BNoise::GetFrequency() {

}

unsigned int BNoise::GetValueNow() {

}

unsigned char BNoise::GetId() {

}

