//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BPWM.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "BPWM.hpp"

unsigned int BPWM::GetValueNow() {

}

unsigned char BPWM::GetId() {

}

unsigned int BPWM::GetFrequency() {

}

unsigned int BPWM::GetValueNow() {

}

unsigned char BPWM::GetId() {

}

