//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ButtonManager.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "ButtonManager.hpp"

void ButtonManager::ButtonPresseMode(){

}

void ButtonManager::Up() {

}

void ButtonManager::Down() {

}

