//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ButtonManager.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "ButtonManager.hpp"

void ButtonManager::ButtonPresseMode(): void() {

}

void ButtonManager::Up() {

}

void ButtonManager::Down() {

}

