//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BWave.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "BWave.hpp"

void BWave::SetFrequency(unsigned int fin) {

}

void BWave::SetDuty(unsigned int duty) {

}

void BWave::SetFrequency(unsigned int fin) {

}

unsigned int BWave::GetFrequency() {

}

unsigned int BWave::GetValueNow() {

}

unsigned char BWave::GetId() {

}

