//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClockSettings.cpp
//  @ Date : 2015/05/29
//  @ Author : 
//
//


#include "ClockSettings.hpp"
#include "sfr_r829.h"

ClockSettings::ClockSettings() {

}

void ClockSettings::Initialize(){
	
	//プロテクトレジスタ
	prc0 = 1;

	//低速オンチップオシレータ起動
	cm14 = 0;

	//高速オンチップオシレータ分周比設定  二分周モード
	//fra20 = 0;
	//fra21 = 0;
	//fra22 = 0;

	//XINクロック有効化
	cm01 = 0;
	cm13 = 1;
	//XINクロック発振開始
	cm05 = 0;


	//高速オンチップオシレータ発振開始
	//fra00 = 1;

	//発振安定まで待機
	for (int i = 0; i < 30; ++i){asm("nop");}

	//高速オンチップオシレータを選択
	//fra01 = 1;

	//XINクロックを選択
	ocd2 = 0;

	//システムクロック分周比選択　分周なし
	cm16 = 0;
	cm17 = 0;

	//8分周OFF設定
	cm06 = 0;

	//レジスタプロテクトON
	prc0 = 0;

}

void ClockSettings::InitializeC(){
	
}

void ClockSettings::SetClock(unsigned long freqency) {

}

unsigned long ClockSettings::GetClock(){
	return 0;
}

