//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FGManager.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "FGManager.hpp"

void FGManager::InsertWaveFromPoolToSlot(unsigned char slot_idx, unsigned char pool_idx) {

}

void FGManager::ConfigureWaveGain(unsigned char slot_idx, float gain_in) {

}

void FGManager::ConfigureWaveFrequencyOrDuty(unsigned char slot_idx, unsiged int freq_in) {

}

void FGManager::ConfigureWavePhase(unsigned char slot_idx, float pahse_in) {

}

void FGManager::DeleteWave(unsigned char slot_idx) {

}

void FGManager::GetWaveStatus(unsigned char slot_idx) {

}

void() FGManager::ButtonPresseMode() {

}

void FGManager::Up() {

}

void FGManager::Down() {

}

