//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : FGManager2.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "FGManager2.hpp"

void FGManager2::button_down_mode() {

}

void FGManager2::button_down_up() {

}

void FGManager2::button_down_down() {

}

void FGManager2::button_down_select() {

}

void FGManager2::move_generator(unsigned char idx) {

}

void FGManager2::clear_output(unsigned char idx) {

}

void FGManager2::clear_all_output() {

}

void FGManager2::set_output_gain(unsigned char idx, float gain) {

}

void FGManager2::set_output_frequency(unsigned char idx, unsigned int freq) {

}

void FGManager2::set_output_phase(unsigned char idx, float phase) {

}

