//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FGState.hpp
//  @ Date : 2015/09/24
//  @ Author : 
//
//

#include "FGState.hpp"

void FGState::SetIndexSelected(unsigned char idx){
	idx_selected = idx;
}

void FGState::SetFunctionGenerator(FunctionGenerator * _fg){
	fg = _fg;
}

void FGState::SetUIUtils(UIUtils *uiu){
	ui_utils = uiu;
}
//###########SLOTS################################
StateSlots::StateSlots(){
	idx_show1 = 0;
	idx_show2 = 1;
	idx_selected = 0;
}
void StateSlots::Initialize(){
	no_slots_max = fg->GetAWaveSlotSize();
}
void StateSlots::Up(){
	if (idx_selected == idx_show1){
		if (idx_show1 == 0){
			idx_show1 = no_slots_max - 1;
		}
		else{
			idx_show1--;
		}
		if (idx_show2 == 0){
			idx_show2 = no_slots_max - 1;
		}
		else{
			idx_show2--;
		}
		idx_selected = idx_show1;
	}
	else{
		idx_selected = idx_show1;
	}
	
}
void StateSlots::Down(){
	if (idx_selected == idx_show2){
		if (idx_show1 == (no_slots_max - 1)){
			idx_show1 = 0;
		}
		else{
			idx_show1++;
		}
		if (idx_show2 == (no_slots_max - 1)){
			idx_show2 = 0;
		}
		else{
			idx_show2++;
		}
	}
	else{
		idx_selected = idx_show2;
	}

}
void StateSlots::Select(){

}
void StateSlots::Mode(){

}


unsigned char StateSlots::GetIndexSelected(){
	return idx_selected;
}

unsigned char StateSlots::GetIndexShow1(){
	return idx_show1;
}
unsigned char StateSlots::GetIndexShow2(){
	return idx_show2;
}
//###########SLOTS################################

//###########FREQUENCY################################
void StateFrequency::Up(){

}
void StateFrequency::Down(){

}
void StateFrequency::Select(){

}
void StateFrequency::Mode(){

}
//###########FREQUENCY################################

//###########PHASE################################
void StatePhase::Up(){

}
void StatePhase::Down(){

}
void StatePhase::Select(){

}
void StatePhase::Mode(){

}
//###########PHASE################################

//###########GAIN################################
void StateGain::Up(){

}
void StateGain::Down(){

}
void StateGain::Select(){

}
void StateGain::Mode(){

}
//###########GAIN################################

//###########DUTYRATIO################################
void StateDutyRatio::Up(){

}
void StateDutyRatio::Down(){

}
void StateDutyRatio::Select(){

}
void StateDutyRatio::Mode(){

}
//###########DUTYRATIO################################

//###########INSERTION################################
void StateInsertion::Up(){

}
void StateInsertion::Down(){

}
void StateInsertion::Select(){

}
void StateInsertion::Mode(){

}
//###########INSERTION################################


unsigned char StateSlots::GetID(){
	return ID_STATE_SLOTS;
}

unsigned char StateFrequency::GetID(){
	return ID_STATE_FREQ;
}

unsigned char StatePhase::GetID(){
	return ID_STATE_PHASE;
}

unsigned char StateGain::GetID(){
	return ID_STATE_GAIN;
}

unsigned char StateDutyRatio::GetID(){
	return ID_STATE_DUTYRATIO;
}

unsigned char StateInsertion::GetID(){
	return ID_STATE_INSERTION;
}





