//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FixedPoint.cpp
//  @ Date : 2015/06/08
//  @ Author : 
//
//


#include "FixedPoint.hpp"

void FixedPoint::SetScale(unsigned int scale) {

}

