//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FunctionGenerator.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "FunctionGenerator.hpp"
#include "AWave.hpp"
#include "BWave.hpp"

void FunctionGenerator::Update() {

}

void FunctionGenerator::InsertWave(unsigned char idx, AWave w) {

}

void FunctionGenerator::InsertWave(unsigned char idx, BWave w) {

}

void FunctionGenerator::DeleteWaveFromSlotMasterIndex(unsigned char idx) {

}

unsigned char FunctionGenerator::GetIdFromSlotMasterIndex(unsigned char idx) {

}

Wave* FunctionGenerator::GetWaveFromSlotMasterIndex(unsigned char idx) {

}

unsigned char FunctionGenerator::GetAWaveSlotSize() {

}

unsigned char FunctionGenerator::GetBWaveSlotSize() {

}

void FunctionGenerator::AUpdate() {

}

void FunctionGenerator::BUpdate() {

}

FunctionGenerator::FunctionGenerator() {

}

