//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : LCDUtils.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "LCDUtils.hpp"

void LCDUtils::Initialize() {

}

void LCDUtils::Write(unsigned char ) {

}

void LCDUtils::Clear() {

}

