//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : SSUbus.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "SSUbus.hpp"

SSUbus::SSUbus(){
	
}

void SSUbus::WriteByte(unsigned char data) {

}

void SSUbus::Write(unsigned char * data, unsigned char bytes) {

}

