//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Super_1.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "Super_1.hpp"

void Super_1::op1() {

}

