//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Timer.cpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#include "Timer.hpp"

void Timer::SetFrequency(unsigned int fin) {

}

void Timer::Enable() {

}

void Timer::Disable() {

}

