//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : UIUtils.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "UIUtils.hpp"
#include "FGManager.hpp"

void UIUtils::Show(FGManager fgm) {

}

