//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : Wave.cpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#include "Wave.hpp"

Wave::Wave()
	:m_is_enabled(false),
	m_is_inserted(false)

{
	;
}

unsigned int Wave::Out() {
	return (m_is_enabled) ? GetValueNow() : 0;
}

void Wave::Enable() {
	m_is_enabled = true;
}

void Wave::Disable() {
	m_is_enabled = false;
}

