//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ANoise.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_ANOISE_H)
#define _ANOISE_H

#include "AWave.hpp"

class ANoise : public AWave {
public:
	ANoise(unsigned int freq, unsigned int phase, float gain);
	unsigned int GetValueNow();
	unsigned char GetId();
private:
	unsigned int count;
};

#endif  //_ANOISE_H
