//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ANone.hpp
//  @ Date : 2015/05/22
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_ANONE_H)
#define _ANONE_H

#include "AWave.hpp"

class ANone : public AWave {
public:
	unsigned int GetValueNow();
	unsigned char GetId();
};

#endif  //_ANONE_H
