//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : APWM.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_APWM_H)
#define _APWM_H

#include "AWave.hpp"

class APWM : public AWave {
public:
	APWM(unsigned int freq, float phase, unsigned int gain);
	unsigned int GetValueNow();
	unsigned char GetId();
	void SetDuty(float d);
private:
	unsigned int m_thre_point;
};

#endif  //_APWM_H
