//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : APWM.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_APWM_H)
#define _APWM_H

#include "AWave.hpp"

class APWM : public AWave {
public:
	APWM(unsigned int freq, unsigned int phase, float gain);
	unsigned int GetValueNow();
	unsigned char GetId();
	void SetDuty(float d);
private:
	float m_thre_point;
};

#endif  //_APWM_H
