//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ASine.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_ASINE_H)
#define _ASINE_H

#include "AWave.hpp"

class ASine : public AWave {
public:
	ASine(const unsigned int *stale, unsigned int nop, unsigned int freq, unsigned int phase, float gain);
	unsigned int GetValueNow();
	unsigned char GetId();
};

#endif  //_ASINE_H
