//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ASine.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_ASINE_H)
#define _ASINE_H

#include "AWave.hpp"



class ASine : public AWave {
public:
	ASine(unsigned int freq, unsigned int phase, unsigned int gain);
	unsigned int GetValueNow();
	unsigned char GetId();

private:
	

};

#endif  //_ASINE_H
