//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : ATriangle.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_ATRIANGLE_H)
#define _ATRIANGLE_H

#include "AWave.hpp"

class ATriangle : public AWave {
public:
	ATriangle(unsigned int freq, unsigned int phase, float gain);
	unsigned int GetValueNow();
	unsigned char GetId();
private:
	bool m_is_countup;
};

#endif  //_ATRIANGLE_H
