//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : AWave.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_AWAVE_H)
#define _AWAVE_H

#include "Wave.hpp"
#include "Clock.hpp"

class AWave : public Wave {
public:
	AWave();
	void SetFrequency(unsigned int fin);
	unsigned int GetFrequency();
	void SetGain(unsigned char gain);
	unsigned int GetGain();
	void SetPhase(float phain);
	float GetPhase();
	unsigned int GetValueNow();
	unsigned char GetId();

	unsigned int Out();


protected:
	Clock m_clk;
private:
	unsigned int m_A;
};

#endif  //_AWAVE_H
