//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ButtonManager.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_BUTTONMANAGER_H)
#define _BUTTONMANAGER_H


class ButtonManager {
public:
	void ButtonPresseMode(): void();
	void Up();
	void Down();
};

#endif  //_BUTTONMANAGER_H
