//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BWave.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_BWAVE_H)
#define _BWAVE_H

#include "Wave.hpp"

class BWave : public Wave {
public:
	void SetFrequency(unsigned int fin);
	void SetDuty(unsigned int duty);
	void SetFrequency(unsigned int fin);
	unsigned int GetFrequency();
	unsigned int GetValueNow();
	unsigned char GetId();
};

#endif  //_BWAVE_H
