//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ClockSettings.hpp
//  @ Date : 2015/05/29
//  @ Author : 
//
//


#if !defined(_CLOCKSETTINGS_H)
#define _CLOCKSETTINGS_H


class ClockSettings {
public:
	unsigned long m_clock;

	ClockSettings();
	
	void Initialize();
	void SetClock(unsigned long freqency);
	unsigned long GetClock();

};

#endif  //_CLOCKSETTINGS_H
