//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : Clock.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_CLOCK_H)
#define _CLOCK_H

//DT‚Í‚±‚±‚ÅŒvŽZ‚·‚é‚æ‚¤‚É‚·‚é

class Clock {
public:
	Clock();
	void SetFreq(unsigned int fin);
	void SetDt();
	void SetNop(unsigned int nopin);
	void SetPhase(unsigned int phain);
	void Set(unsigned int fin, unsigned int nopin, unsigned int phain);
	unsigned int GetFreq();
	float GetDt();
	unsigned int GetNop();
	unsigned int GetPhase();
	unsigned int Update();
private:
	unsigned int m_nop;
	float m_dt;
	float m_pinv;
	unsigned int m_f;
	unsigned int m_k;
	float m_phase;
	unsigned int m_phase_shift_point;
};

#endif  //_CLOCK_H
