//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : Dac.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_DAC_H)
#define _DAC_H

#include "SSUbus.hpp"

class Dac {
public:
	void WriteVoltage(unsigned int vol);
private:
	SSUbus m_ssu;
};

#endif  //_DAC_H
