//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FGManager.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_FGMANAGER_H)
#define _FGMANAGER_H


class FGManager {
public:
	unsigned char m_mode;
	void InsertWaveFromPoolToSlot(unsigned char slot_idx, unsigned char pool_idx);
	void ConfigureWaveGain(unsigned char slot_idx, float gain_in);
	void ConfigureWaveFrequencyOrDuty(unsigned char slot_idx, unsigned int freq_in);
	void ConfigureWavePhase(unsigned char slot_idx, float pahse_in);
	void DeleteWave(unsigned char slot_idx);
	void GetWaveStatus(unsigned char slot_idx);
	void ButtonPresseMode();
	void Up();
	void Down();
};

#endif  //_FGMANAGER_H
