//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : FGManager.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_FGMANAGER_H)
#define _FGMANAGER_H

#include "UIUtils.hpp"
#include "FunctionGenerator.hpp"

class FGManager {
public:
	FGManager();
	void InsertWaveFromPoolToSlot(unsigned char slot_idx, unsigned char pool_idx);
	void ConfigureWaveGain(unsigned char slot_idx, float gain_in);
	void ConfigureWaveFrequencyOrDuty(unsigned char slot_idx, unsigned int freq_in);
	void ConfigureWavePhase(unsigned char slot_idx, float pahse_in);
	void DeleteWave(unsigned char slot_idx);
	void GetWaveStatus(unsigned char slot_idx);

	void Mode();
	void Select();
	void Up();
	void Down();

	void SetFunctionGenerator(FunctionGenerator *pfg);




private:

	UIUtils uiu;
	UISet uis;
	UIView uiv;
	UIInsertion uii;



	FunctionGenerator *fg;
	unsigned char m_mode;
	unsigned char m_slot;
	unsigned char m_pool;
	unsigned char m_scale;

	void IncrementGain();
	void DecrementGain();
	void IncrementFrequency();
	void DecrementFrequency();
	void ChangeScaleGain();
	void ChangeScaleFrequency();


};

#endif  //_FGMANAGER_H
