//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FGStateMachine.hpp
//  @ Date : 2015/09/24
//  @ Author : 
//
//


#if !defined(_FGSTATEMACHINE_H)
#define _FGSTATEMACHINE_H

#include "FGState.hpp"
#include "Timer.hpp"
#include "FunctionGenerator.hpp"
#include "KeyInterruption.hpp"
#include "UIUtils.hpp"
//#include "LCDUtils.hpp"

class INTRfg : public FunctionGenerator, public INTRbase{
public:
	INTRfg() : FunctionGenerator(){};

	void op(){
		Update();
	}
};

class FGStateMachine{
public:
	FGStateMachine();
	void Up();
	void Down();
	void Select();
	void Mode();
private:
	unsigned char idx_selected;
	FGState * state_now;
	StateSlots state_slots;
	StateFrequency state_freq;
	StatePhase state_phase;
	StateGain state_gain;
	StateDutyRatio state_dutyratio;
	StateInsertion state_insertion;

	Timer tim;
	static INTRfg fg;

	UIUtils ui_utils;

	void TransitState();
};

#endif  //_FGSTATEMACHINE_H
