//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FixedPoint.hpp
//  @ Date : 2015/06/08
//  @ Author : 
//
//


#if !defined(_FIXEDPOINT_H)
#define _FIXEDPOINT_H


class FixedPoint {
	unsigned long m_v;
	unsigned char m_scale; //‰½‰ñƒVƒtƒg‚·‚é‚©
public:
	void SetScale(unsigned int scale);
};

#endif  //_FIXEDPOINT_H
