//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : FunctionGenerator.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_FUNCTIONGENERATOR_H)
#define _FUNCTIONGENERATOR_H

#include "AWave.hpp"
#include "BWave.hpp"
#include "Dac.hpp"
#include "Timer.hpp"
#include "Settings.hpp"

#include "ASawtooth.hpp"
#include "ASine.hpp"
#include "ATriangle.hpp"
#include "APWM.hpp"
#include "ANoise.hpp"
#include "ANone.hpp"

class FunctionGenerator {
public:
	FunctionGenerator();
	void Update();
	void InsertWave(unsigned char idx, AWave* w);
	void InsertWave(unsigned char idx, BWave* w);
	void InsertWaveFromPoolToSlotMasterIndex(unsigned char slot_idx, unsigned char pool_idx);
	void DeleteWaveFromSlotMasterIndex(unsigned char idx);
	unsigned char GetIdFromSlotMasterIndex(unsigned char idx);
	Wave* GetWaveFromSlotMasterIndex(unsigned char idx);
	Wave* GetWaveFromPoolMasterIndex(unsigned char idx);
	unsigned char GetAWaveSlotSize();
	unsigned char GetBWaveSlotSize();
private:

	ANone m_anone;
	ASawtooth m_asawtooth;
	ASine m_asine;
	ATriangle m_atriangle;
	APWM m_apwm;
	ANoise m_anoise;


	Dac m_dac;
	//Timer m_tim;
	AWave* m_aslot[Settings::FG_MAX_SLOT];
	BWave* m_bslot;
	Wave* m_pool_wave[Settings::FG_MAX_POOL];
	void AUpdate();
	void BUpdate();
	unsigned char GetNoW();
	
};

#endif  //_FUNCTIONGENERATOR_H
