//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KeyInterruption.hpp
//  @ Date : 2015/06/24
//  @ Author : 
//
//


#if !defined(_KEYINTERRUPTION_H)
#define _KEYINTERRUPTION_H

class BtnEvent{
public:
	virtual void mode() = 0;
	virtual void select() = 0;
	virtual void up() = 0;
	virtual void down() = 0;
};

class KeyInterruption {
public:
	KeyInterruption();
	void Initialize();

	void SetEvent(BtnEvent * be);

	void Enable();
};

#endif  //_KEYINTERRUPTION_H
