//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KeyInterruption.hpp
//  @ Date : 2015/06/24
//  @ Author : 
//
//


#if !defined(_KEYINTERRUPTION_H)
#define _KEYINTERRUPTION_H

#include "Timer.hpp"

class KeyInterruption {
public:
	KeyInterruption();
	void Initialize();
	void SetEventMode(INTRbase * pib);
	void SetEventSelect(INTRbase * pib);
	void SetEventUp(INTRbase * pib);
	void SetEventDown(INTRbase * pib);

	void Enable();
};

#endif  //_KEYINTERRUPTION_H
