//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : LCDUtils.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_LCDUTILS_H)
#define _LCDUTILS_H


class LCDUtils {
public:
	void Initialize();
	void Write(unsigned char );
	void Clear();
};

#endif  //_LCDUTILS_H
