//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Settings.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_SETTINGS_H)
#define _SETTINGS_H


class Settings {
public:
	static const unsigned char SLOT_SIZE_MAX;
	static const unsigned char WAVE_ID_ANONE;
	static const unsigned char WAVE_ID_ASINE;
	static const unsigned char WAVE_ID_ATRIANGLE;
	static const unsigned char WAVE_ID_ASAWTOOTH;
	static const unsigned char WAVE_ID_APWM;
	static const unsigned char WAVE_ID_ANOISE;
	static const unsigned char WAVE_ID_BNONE;
	static const unsigned char WAVE_ID_BPWM;
	static const unsigned char WAVE_ID_BNOISE;


};

#endif  //_SETTINGS_H
