//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : Settings.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_SETTINGS_H)
#define _SETTINGS_H


class Settings {
public:
	static const unsigned char SLOT_SIZE_MAX;
	static const unsigned char WAVE_ID_ANONE = 0xA0;
	static const unsigned char WAVE_ID_ASINE = 0xA1;
	static const unsigned char WAVE_ID_ATRIANGLE = 0xA2;
	static const unsigned char WAVE_ID_ASAWTOOTH = 0xA3;
	static const unsigned char WAVE_ID_APWM = 0xA4;
	static const unsigned char WAVE_ID_ANOISE = 0xA5;
	static const unsigned char WAVE_ID_BNONE = 0xA6;
	static const unsigned char WAVE_ID_BPWM = 0xA7;
	static const unsigned char WAVE_ID_BNOISE = 0xA8;

	static const unsigned char FG_MAX_SLOT = 5;
	static const unsigned char FG_MAX_POOL = 6;

	static const unsigned long CLOCK_MAIN_HZ = 20000000;
	
		
	
	
};

#endif  //_SETTINGS_H
