//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : SSUbus.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_SSUBUS_H)
#define _SSUBUS_H


class SSUbus {
public:
	SSUbus();
	void WriteByte(unsigned char data);
	void Write(unsigned char * data, unsigned char bytes);
};

#endif  //_SSUBUS_H
