//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : SSUbus.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_SSUBUS_H)
#define _SSUBUS_H


class SSUbus {
public:
	SSUbus(unsigned char mode);
	SSUbus();
	void InitializeSynchronizedClockMode();
	void Initialize4WiresMode();
	void WriteByte(unsigned char data);
	void Write(unsigned char * data, unsigned char bytes);
	void WriteSync(unsigned int word);

	static void SInitializeSynchronizedClockMode();
	static void SWriteSync(unsigned int word);

	static const unsigned char MODE_SYNCHRONIZED_CLOCK = 0x01;
	static const unsigned char MODE_4WIRES = 0x02;

};

#endif  //_SSUBUS_H
