//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SSUbus.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_SSUBUS_H)
#define _SSUBUS_H


class SSUbus {
public:
	void WriteByte(unsigned char data);
	void Write(unsigned char data, unsigned char bytes);
};

#endif  //_SSUBUS_H
