//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : Super.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_SUPER_H)
#define _SUPER_H


class Super {
public:
	int foo;
private:
	void op1();
};

#endif  //_SUPER_H
