//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Super_1.hpp
//  @ Date : 2015/05/25
//  @ Author : 
//
//


#if !defined(_SUPER_1_H)
#define _SUPER_1_H


class Super_1 {
public:
	int foo;
private:
	void op1();
};

#endif  //_SUPER_1_H
