//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : Timer.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_TIMER_H)
#define _TIMER_H

#include "Dac.hpp"

class Timer {
public:
	Timer();
	
	void Enable();
	void Disable();
	void SetDt(float dt_ms);
	float GetDt();

	volatile void IntrTB();

private:
	Dac m_dac;

	unsigned int m_tmp;

};

#endif  //_TIMER_H
