//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : UIUtils.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_UIUTILS_H)
#define _UIUTILS_H

#include "FGManager.hpp"

class UIUtils {
public:
	void Show(FGManager fgm);
};

#endif  //_UIUTILS_H
