//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  Project : Function Generator
//  @ File Name : UIUtils.hpp
//  @ Date : 2015/05/25
//  @ Author : Kazuki Kikuchi
//
//


#if !defined(_UIUTILS_H)
#define _UIUTILS_H

//#include "FGManager.hpp"
#include "LCDUtils.hpp"
#include "AWave.hpp"

class UIView{
public:
	void Set(Wave *w, unsigned char slotnum);
	Wave * GetWave();
	unsigned char GetSlotNumber();
private:
	Wave *m_awave;
	unsigned char m_slotnum;
};

class UISet{
public:
	void Set(Wave *w, unsigned char slotnum, unsigned char ui_mode);
	void Set(Wave *w, unsigned char slotnum, unsigned char ui_mode, unsigned char scl);
	Wave * GetWave();
	unsigned char GetSlotNumber();
	unsigned char GetMode();
	unsigned char m_scale;
private:
	Wave *m_awave;
	unsigned char m_slotnum;
	unsigned char m_ui_mode;
};

class UIInsertion{
public:
	void Set(Wave *w_selected, Wave *w);
	Wave * GetWaveSelected();
	Wave * GetWave();
private:
	Wave *m_w_selected, *m_w;
};


class UIUtils {
public:
	UIUtils();
	//void Show(FGManager fgm);

	void Output(UIView * ui);
	void Output(UISet * ui);
	void Output(UIInsertion * ui);

	void WriteWaveNameFromID(const unsigned char ID);
	void WriteWaveNameFromSelectedID(const unsigned char ID);

	LCDUtils * GetHundleLCD();

	static const unsigned char UI_MODE_UNDEFINED = 0x00;
	static const unsigned char UI_MODE_VIEW = 0x01;
	static const unsigned char UI_MODE_FREQUENCY = 0x02;
	static const unsigned char UI_MODE_GAIN = 0x03;
	static const unsigned char UI_MODE_INSERTION = 0x04;

	void WriteFrequency2(unsigned int f, unsigned char scale);
	const char * GetTextFromID(unsigned char ID);
private:

	LCDUtils lcd;
	//8•¶Žš‚Ü‚Å
	const char * WAVE_TEXT_ANONE;
	const char * WAVE_TEXT_ASINE;
	const char * WAVE_TEXT_ATRIANGLE;
	const char * WAVE_TEXT_ASAWTOOTH;
	const char * WAVE_TEXT_APWM;
	const char * WAVE_TEXT_ANOISE;
	const char * WAVE_TEXT_GAIN;
	const char * WAVE_TEXT_FREQ;
	const char * WAVE_TEXT_POOL;
	const char * WAVE_TEXT_SLOT;
	const char * WAVE_TEXT_SET;

	

	void WriteFrequency(unsigned int f);
	//void WriteFrequency2(unsigned int f, unsigned char scale);
	void WriteGain2(unsigned int gain, unsigned char scale);

};




#endif  //_UIUTILS_H
